--- !map:Settings 
group_order: 
- main
- subject
- notes
- control
groups: 
  main: 
    all_tags: 
    - "100"
    - "700"
    - "240"
    - "730"
    - "260"
    - "300"      
    - "337"
    - "210"
  subject:
    all_tags:
    - "020"
    - "022"
    - "024"
    - "041"
    - "044"
    - "710"
    - "760"
    - "650"
    - "651"
    - "250" 
    - "780" 
    - "785" 
  control: 
    all_tags: 
    - "000"
    - "001"
    - "003"
    - "005"
  notes: 
    all_tags: 
    - "500"
    - "502"
    - "599"
    - "856"
    - "520"
